#!/bin/bash

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Set EXA_COLORS
#
#  - The actual colors are configured through the `EXA_COLORS`
#    environment variable (built-in defaults are used if this
#    variable is not set)

EXA_COLORS=""

# File sizes
EXA_COLORS+="sn=38;5;36:"
EXA_COLORS+="sb=38;5;209:"

# Owners and groups
EXA_COLORS+="uu=38;5;136:"
EXA_COLORS+="un=38;5;168:"
EXA_COLORS+="gu=38;5;136:"
EXA_COLORS+="gn=38;5;168:"

# Permissions
EXA_COLORS+="ur=38;5;172:"
EXA_COLORS+="uw=38;5;172:"
EXA_COLORS+="ux=38;5;172:"
EXA_COLORS+="ue=38;5;172:"
EXA_COLORS+="gr=38;5;74:"
EXA_COLORS+="gw=38;5;74:"
EXA_COLORS+="gx=38;5;74:"
EXA_COLORS+="tr=38;5;168:"
EXA_COLORS+="tw=38;5;168:"
EXA_COLORS+="tx=38;5;168:"
# EXA_COLORS+="su=38;5;239"
# EXA_COLORS+="sf=38;5;239"
# EXA_COLORS+="xa=38;5;242"

# Git
EXA_COLORS+="ga=38;5;196:"
EXA_COLORS+="gm=38;5;220:"
EXA_COLORS+="gv=38;5;39:"

# Hard links
EXA_COLORS+="lc=38;5;160:"

# Details and Metadata
EXA_COLORS+="bO=48;5;124:"
EXA_COLORS+="da=38;5;242:"
# EXA_COLORS+="lp=38;5;30:"

# File class
EXA_COLORS+="fi=38;5;251:"
EXA_COLORS+="di=38;5;75:"
EXA_COLORS+="ex=38;5;43:"
EXA_COLORS+="pi=38;5;154:"
EXA_COLORS+="so=38;5;199:"
# EXA_COLORS+="bd=38;5;135:"
# EXA_COLORS+="cd=38;5;135:"
EXA_COLORS+="ln=38;5;214:"
EXA_COLORS+="or=48;5;124:"

# Reset all file types
EXA_COLORS+="*=38;5;251:"

export EXA_COLORS

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Load OS specific colors

. "colors/$OS/bash_colors"
