#!/bin/bash

if [ -f "autocomplete/$OS/bash_autocomplete" ]; then
    . "autocomplete/$OS/bash_autocomplete"
fi

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

if [ -d "profile.d" ]; then

    # Source all profile.d scripts on login

    for i in profile.d/*.sh; do
        if [ -f "$i" ]; then
            . "$i"
        fi
    done

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    # Source completion scripts only if the shell is interactive

    if [[ $- == *i* && -d "profile.d/completion" ]]; then

        for i in profile.d/completion/*.sh; do
            if [ -f "$i" ]; then
                . "$i"
            fi
        done

    fi

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    unset i

fi



if [ -f "../git/git-completion.sh" ]; then
    . "../git/git-completion.sh"
    __git_complete g __git_main
fi
