# https://alacritty.org/config-alacritty.html

[window]
padding = { x = 3, y = 0 }
startup_mode = "Maximized"
option_as_alt = "Both"  # macOS only

[font]
size = 19
offset = { x = 0, y = 0 }
normal      = { family = "IosevkaTerm Nerd Font Mono", style = "Light" }
italic      = { style = "Light Italic" }
bold        = { style = "Bold" }
bold_italic = { style = "Bold Italic" }

[colors.primary]
background = "#1a1a1a"
foreground = "#b0b0b0"

[colors.normal]
black   = "#222222"
red     = "#ef6060"
green   = "#4ab54a"
yellow  = "#ceb044"
blue    = "#45a1ed"
magenta = "#c678dd"
cyan    = "#56b6c2"
white   = "#dddddd"

[colors.bright]
black   = "#5a5a5a"
red     = "#e06c75"
green   = "#98c379"
yellow  = "#d19a66"
blue    = "#61afef"
magenta = "#c678dd"
cyan    = "#56b6c2"
white   = "#e6efff"

[mouse]
hide_when_typing = true

[keyboard]
# See default keyboard bindings
# https://alacritty.org/config-alacritty-bindings.html
bindings = [
  # <Ctrl-I> and <Tab> emit the same ASCII code, so Neovim opens buffer list on
  # pressing <Ctrl-I> because we have mapped <Tab> to open buffer list. However
  # we want to move forward in the Neovim jumplist upon pressing <Ctrl-I> which
  # is the default behavior of Neovim. So here we instruct alacritty to send a
  # custom escape sequence on pressing <Ctrl-I>. We then catch this custom
  # escape sequence in Neovim, and use it to simulate pressing <Ctrl-I> inside
  # Neovim. This makes Neovim move forward in the jumplist.
  # https://vi.stackexchange.com/a/25015
  { key = "I", mods = "Control", chars = "\u000e\u0069" },
]
