#!/usr/bin/env bash

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Check if the given command exists.

cmd_exists() {
    command -v "$1" &> /dev/null
}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Create data URI from a file.

datauri() {

    local mimeType=""

    if [ -f "$1" ]; then
        mimeType=$(file -b --mime-type "$1")
        #                └─ do not prepend the filename to the output

        if [[ $mimeType == text/* ]]; then
            mimeType="$mimeType;charset=utf-8"
        fi

        printf "data:%s;base64,%s" \
            "$mimeType" \
            "$(openssl base64 -in "$1" | tr -d "\n")"
    else
        printf "%s is not a file" "$1"
    fi

    printf "\n"

}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Sort the files/directories by file size

dus() {
    du -sh "$@" | sort -hr
}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Execute arithmetic operations

eq() {
    set -f
    echo "$@" | bc
    set +f
}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Fuzzy find files, then once selected edit it in your preferred editor

fzf_find_edit() {

    local files=$(
        if [ "$FZF_PREVIEW" -eq 1 ]; then
            fzf --multi --preview 'bat --color=always --line-range :500 {}'
        else
            fzf --multi
        fi
    )

    if [[ -n $files ]]; then
        # shellcheck disable=SC2086
        ${EDITOR:-vim} $files
    fi

}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Fuzzy git add

fzf_git_add() {

    local files=$(
        git ls-files \
            --deleted \
            --modified \
            --others \
            --killed \
            --directory \
            --no-empty-directory |
            sort --unique |
            fzf --ansi
    )

    if [[ -n $files ]]; then
        # shellcheck disable=SC2086
        git add --verbose $files
    fi

}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Fuzzy git diff

fzf_git_diff() {

    # https://stackoverflow.com/a/45111524

    local files=$(
        git diff "$@" --name-only |
            xargs -I '{}' realpath \
                --relative-to=. "$(git rev-parse --show-toplevel)"/'{}' |
            fzf --ansi --no-sort --height 100% \
                --preview "echo {} |
                    xargs -I@ sh -c 'git d $* --color=always @'"
    )

    if [[ -n $files ]]; then
        # shellcheck disable=SC2086
        git d "$@" $files
    fi

}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Fuzzy search in git logs.

fzf_git_log() {

    local commits=$(
        if [ "$FZF_PREVIEW" -eq 1 ]; then
            git l --color=always "$@" |
                fzf --ansi --no-sort --height 100% \
                    --preview "echo {} |
                        grep -o '[a-f0-9]\{7\}' |
                        head -1 |
                        xargs -I@ sh -c 'git sh --color=always @'"
        else
            git l --color=always "$@" |
                fzf --ansi --no-sort --height 100%
        fi
    )

    if [[ -n $commits ]]; then
        local hashes=$(printf "%s" "$commits" | cut -d' ' -f2 | tr '\n' ' ')
        # shellcheck disable=SC2086
        git sh $hashes
    fi

}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Fuzzy search in git pickaxe.

fzf_git_log_pickaxe() {

    if [[ $# == 0 ]]; then
        echo 'Error: search term was not provided.'
        return
    fi

    local commits=$(
        if [ "$FZF_PREVIEW" -eq 1 ]; then
            git log --pretty=custom --color=always -S "$@" |
                fzf --ansi --no-sort --height 100% \
                    --preview "git sh --color=always {1}"
        else
            git log --pretty=custom --color=always -S "$@" |
                fzf --ansi --no-sort --height 100%
        fi
    )

    if [[ -n $commits ]]; then
        local hashes=$(printf "%s" "$commits" | cut -d' ' -f1 | tr '\n' ' ')
        # shellcheck disable=SC2086
        git sh $hashes
    fi

}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Fuzzy git reflog.

fzf_git_reflog() {

    local hash=$(
        if [ "$FZF_PREVIEW" -eq 1 ]; then
            git rf --color=always "$@" |
                fzf --ansi --no-sort --height 100% \
                    --preview "git sh --color=always {1}"
        else
            git reflog --color=always "$@" |
                fzf --no-multi --ansi --no-sort --height 100%
        fi
    )

    echo "$hash"

}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Fuzzy git reset.

fzf_git_reset() {

    local files=$(
        git diff --name-only --cached |
            xargs -I '{}' realpath --relative-to=. "$(git rev-parse --show-toplevel)"/'{}' |
            sort --unique |
            fzf --ansi
    )

    if [[ -n $files ]]; then
        # shellcheck disable=SC2086
        git reset $files
    fi

}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Fuzzy find a file, with colorful preview, that contains the supplied
# term, then once selected edit it in your preferred editor.
# Note, if your EDITOR is Vim or Neovim then you will be automatically
# scrolled to the selected line.

fzf_grep_edit(){

    if [[ $# == 0 ]]; then
        echo 'Error: search term was not provided.'
        return
    fi

    local matches
    if cmd_exists "rg"; then
        matches=$(
            if [ "$FZF_PREVIEW" -eq 1 ]; then
                rg --color=never --line-number "$1" |
                    fzf --delimiter : \
                    --preview "bat --color=always --line-range {2}: {1}"
            else
                rg --color=never --line-number "$1" |
                    fzf --delimiter :
            fi
        )
    else
        matches=$(
            if [ "$FZF_PREVIEW" -eq 1 ]; then
                ag --nobreak --noheading "$1" |
                    fzf --delimiter : \
                    --preview "bat --color=always --line-range {2}: {1}"
            else
                ag --nobreak --noheading "$1" |
                    fzf --delimiter :
            fi
        )
    fi

    # https://stackoverflow.com/a/28101809

    files=$(echo "$matches" \
        | cut -d':' -f1,2 \
        | sed 's/:/|:/' \
        | sed 's/^/:e /' \
        |sed 's/$/|/')

    if [[ -n $files ]]; then
        ${EDITOR:-vim} -c "$files" +/"$1"
    fi

}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Get gzip information (gzipped file size + reduction size).

gz() {

    declare -i gzippedSize=0
    declare -i originalSize=0

    if [ -f "$1" ]; then
        if [ -s "$1" ]; then

            originalSize=$( wc -c < "$1" )
            printf "\n original size:   %12s\n" "$(hrfs "$originalSize")"

            gzippedSize=$( gzip -c "$1" | wc -c )
            printf " gzipped size:    %12s\n" "$(hrfs "$gzippedSize")"

            printf " ─────────────────────────────\n"
            printf " reduction:       %12s [%s%%]\n\n" \
                "$( hrfs $((originalSize - gzippedSize)) )" \
                "$( printf "%s" "$originalSize $gzippedSize" | \
                    awk '{ printf "%.1f", 100 - $2 * 100 / $1 }' | \
                    sed -e "s/0*$//;s/\.$//" )"
                    #              └─ remove tailing zeros

        else
            printf "\"%s\" is empty.\n" "$1"
        fi
    else
        printf "\"%s\" is not a file.\n" "$1"
    fi

}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Human readable file size
# (because `du -h` doesn't cut it for me).

hrfs() {

    printf "%s" "$1" |
    awk '{
            i = 1;
            split("B KB MB GB TB PB EB ZB YB WTFB", v);
            value = $1;

            # confirm that the input is a number
            if ( value + .0 == value ) {

                while ( value >= 1024 ) {
                    value/=1024;
                    i++;
                }

                if ( value == int(value) ) {
                    printf "%d %s", value, v[i]
                } else {
                    printf "%.1f %s", value, v[i]
                }

            }
        }' |
    sed -e ":l" \
        -e "s/\([0-9]\)\([0-9]\{3\}\)/\1,\2/; t l"
    #    └─ add thousands separator
    #       (changes "1023.2 KB" to "1,023.2 KB")

}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Create new directories and enter the first one.

mkd() {
    if [ -n "$*" ]; then

        mkdir -p "$@"
        #      └─ make parent directories if needed

        cd "$@" \
            || exit 1

    fi
}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Open files using mupdf

mu() {

    if [ "$#" -eq 0 ]; then
        echo "Please provide at least one file";
    else
        mupdf-x11 "$@" &> /dev/null &
    fi

}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Kill all processes by name

nkill() {

    if [ -z "$1" ]; then
        echo "Please specify name of a process";
    else
        processes_count="$(nlist "$1" -u | wc -l)"

        if [ "$processes_count" -eq 0 ]; then
            print_in_cyan " No matching process found that belongs to you\n"
        else

            ask_for_confirmation "$processes_count processes can be killed. Are you sure you want to kill them?"
            if answer_is_yes; then
                nlist "$1" -u | awk '{print $2}' | xargs kill -9
            fi

        fi

    fi

}


# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# List all processes by name

nlist() {

    if [ -z "$1" ]; then
        echo "Please specify name of a process";
    else

        # Modify the input string so that it's result is not shown
        # in the grep output
        # https://unix.stackexchange.com/a/74186

        local name="$1"
        name="[${name:0:1}]${name:1:${#name}}"

        local args="auxw"
        if [ "$2" == "-u" ]; then
            args="uxw"
        fi

        # shellcheck disable=SC2009
        ps "$args" | grep "$name"

    fi

}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Set PS1 prompt

ps1() {
    set_prompts "$@"
}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Install nix packages

xei() {

    local args=""

    for i in "$@"; do
        args="$args nixpkgs.$i"
    done

    echo "nix-env -iA$args"

    echo "$args" | xargs nix-env -iA

}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Search nix packages

xes() {
    nix-env -qaP ".*($1).*" | fzf
}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Switch directories on the basis of frecency
# https://github.com/rupa/z

# Unalias `z` command defined by the script
unalias z 2> /dev/null

z() {

    [ $# -gt 0 ] \
        && _z "$@" \
        && return

    # shellcheck disable=SC2164
    cd "$(_z -l 2>&1 \
            | sed 's/^[0-9,.]* *//' \
            | awk '{a[i++]=$0} END {for (j=i-1; j>=0;) print a[j--] }' \
            | fzf)"

}
